### ISSUE TITLE
Empty slashes in resource property when using NewAPI( "v1" )

### ISSUE THREAD

**Issue by ben-crowhurst** [univedo/api2go#73] opened 2015-03-12 14:13 UTC
> api := api2go.NewAPI("v1")
> api.AddResource(model.App{}, &controller.AppCtrl{})
> api.AddResource(model.Feed{}, &controller.FeedCtrl{})
>  api.AddResource(model.Profile{}, &controller.ProfileCtrl{})
>
>   http.ListenAndServe(":8080", api.Handler())

>package controller
>type ProfileCtrl struct {
>    profiles map[string]*model.Profile
>}
>
> func (s *ProfileCtrl) FindAll(request api2go.Request) (interface{}, error) {
>    profile := model.Profile
>    profile.Forename = "Ben"
>    ...
>    
>    return profile, status
> }

curl http://localhost:8080/v1/profiles

{"data":{"email":"xxxxx@corvusoft.co.uk","forename":"Ben","id":"96329b3e-c25b-4b22-91a1-c8ffa6aa7fb3","lastLocationHref":"","license":"trial","links":{"apps":{"ids":["050f2861-8c5c-445b-9643-a0495748e38"],**"resource":"/v1//profiles/96329b3e-c25b-4b22-91a1-c8ffa6aa7fb3/apps"**,"type":"apps"}},"organisation":"Corvusoft Solutions","surname":"Crowhurst","type":"profiles"}

**Comment by sharpner** [comment] 2015-03-12 14:37
Could you provide more of your code? Which call is it?

**Comment by sharpner** [comment] 2015-03-16 20:48
Ah I see you updated your original message. Will look into it.

**Comment by wwwdata** [comment] 2015-03-17 14:24
hm, I have changed the api tests to use a prefix and the `resource` url seems to be generated fine without double slashes. Can you give me a complete code example where this error happens? It would be ideal if you could write a unit test that fails, then we could correct the code until it works.

**Comment by sharpner** [comment] 2015-03-17 16:03
I couldn't reproduce it either. Is this still a problem or have you fixed it already @ben-crowhurst ?

**Comment by ben-crowhurst** [comment] 2015-03-17 16:05
Still a problem.  I'll setup a testcase.

**Comment by sharpner** [comment] 2015-03-17 16:06
thanks

**Comment by ben-crowhurst** [comment] 2015-03-18 18:04
Well, having sat down and created the test case. I too fail to replicate this issue.  When into the office tomorrow morning I'll `go get` and see if it resolves itself there as-well.

Please leave this ticket open until COB Thursday 18th March 2015.

**Comment by sharpner** [comment] 2015-03-18 19:49
Please make sure to go get -u github.com/univedo/api2go before testing again. 

Maybe you had this problem with an older Version ;-)

**Comment by sharpner** [comment] 2015-03-19 16:48
ok closing this.

**Closed by sharpner** 2015-03-19 16:48 UTC
Labels: bug

**Comment by ben-crowhurst** [comment] 2015-03-19 18:49
All,

Sorry I was meaning to get to this today.  Will confirm tomorrow and reopen if necessary.  Thank you for your time

Regards,
Ben Crowurst
Corvusoft Solutions
